import type { Metadata } from 'next';
import { LegalPage } from '@/components/legal-page';
import { productBrand } from '@/lib/brand';
import styles from '@/components/legal-page.module.css';

export const metadata: Metadata = {
  title: `Terms of Service | ${productBrand.name}`,
  description: `Terms for using ${productBrand.name}'s AI cofounder workspace, subscriptions, credits, integrations, and generated outputs.`,
};

const toc = [
  { href: '#agreement', label: 'Agreement' },
  { href: '#services', label: 'Services' },
  { href: '#accounts', label: 'Accounts' },
  { href: '#content', label: 'Content' },
  { href: '#ai', label: 'AI Outputs' },
  { href: '#acceptable-use', label: 'Acceptable Use' },
  { href: '#billing', label: 'Billing' },
  { href: '#third-party', label: 'Third Parties' },
  { href: '#ip', label: 'IP' },
  { href: '#termination', label: 'Termination' },
  { href: '#disclaimers', label: 'Disclaimers' },
  { href: '#liability', label: 'Liability' },
  { href: '#law', label: 'Governing Law' },
  { href: '#contact', label: 'Contact' },
] as const;

export default function TermsOfServicePage() {
  return (
    <LegalPage
      description={`These terms set the rules for using ${productBrand.name}'s AI cofounder workspace, including account responsibilities, content ownership, credits, subscriptions, acceptable use, AI limitations, and dispute mechanics.`}
      documentTitle={`${productBrand.name} Terms of Service`}
      eyebrow="Legal"
      lastUpdated="August 5, 2026"
      relatedHref="/privacy"
      relatedLabel="Privacy"
      title="Terms of Service"
      toc={toc}
    >
      <section id="agreement">
        <h2>1. Agreement to These Terms</h2>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of {productBrand.name}&apos;s websites, applications, AI agents, integrations, billing features, support channels, and related services (collectively, the &quot;Services&quot;) provided by {productBrand.name} (&quot;{productBrand.name},&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;).
        </p>
        <p>
          By creating an account, clicking &quot;Sign up,&quot; &quot;Continue,&quot; &quot;Subscribe,&quot; or similar buttons, or by accessing or using the Services, you agree to these Terms and our Privacy Policy. If you do not agree, do not use the Services.
        </p>
        <p>
          If you use the Services on behalf of a company or other organization, you represent that you have authority to bind that organization. In that case, &quot;you&quot; refers to both you and that organization.
        </p>
      </section>

      <section id="services">
        <h2>2. Our Services</h2>
        <p>
          {productBrand.name} provides an AI cofounder and decision assistant workspace. The Services may help you research markets, analyze competitors, find users, draft plans, process connected work context, generate content, summarize materials, and make decisions.
        </p>
        <p>
          The Services are productivity and decision-support tools. They do not replace professional legal, financial, accounting, medical, investment, hiring, security, or other expert advice. You are responsible for evaluating outputs and deciding how to act.
        </p>
        <p>
          We may change, suspend, discontinue, or limit parts of the Services at any time. We may also introduce new features, usage limits, credits, plans, or eligibility requirements.
        </p>
      </section>

      <section id="accounts">
        <h2>3. Accounts and Security</h2>
        <ul>
          <li>You must provide accurate account information and keep it up to date.</li>
          <li>You are responsible for maintaining the confidentiality of your account, credentials, devices, and connected services.</li>
          <li>You are responsible for all activity under your account unless caused by our breach of these Terms.</li>
          <li>You must promptly notify us if you suspect unauthorized access or security issues.</li>
          <li>You may not transfer, sell, rent, or share your account except as allowed by your plan or by a written agreement with us.</li>
        </ul>
        <p>
          The Services are not intended for users under 18. You may not use the Services if you are under 18.
        </p>
      </section>

      <section id="content">
        <h2>4. Your Content and Generated Outputs</h2>
        <p>
          &quot;Your Content&quot; means prompts, messages, files, links, notes, connected-service data, instructions, feedback, and other materials that you submit to or make available through the Services. &quot;Outputs&quot; means content generated by the Services in response to Your Content.
        </p>
        <p>
          As between you and {productBrand.name}, you retain ownership of Your Content. To the extent permitted by applicable law and subject to third-party rights, you also own the Outputs generated for you by the Services.
        </p>
        <p>
          You grant {productBrand.name} a limited, worldwide, non-exclusive, royalty-free license to host, store, reproduce, process, transmit, display, and otherwise use Your Content and Outputs only as reasonably necessary to provide, secure, maintain, support, and improve the Services; comply with law; enforce these Terms; and prevent abuse.
        </p>
        <div className={styles.callout}>
          Your private tasks, files, projects, playbooks, and decision history are private by default. They become visible to others only if you share them, publish them, invite collaborators, connect a team workspace, or otherwise authorize disclosure.
        </div>
        <p>
          You represent that you have all rights and permissions necessary to submit Your Content to the Services and to authorize the processing described in these Terms and our Privacy Policy.
        </p>
      </section>

      <section id="ai">
        <h2>5. AI Outputs and Decision Responsibility</h2>
        <p>
          AI systems can produce inaccurate, incomplete, biased, offensive, non-unique, or legally problematic outputs. Outputs may not reflect current facts and may not be suitable for your specific circumstances.
        </p>
        <ul>
          <li>You are responsible for reviewing, validating, and approving Outputs before relying on them or sharing them.</li>
          <li>You are responsible for decisions you make using the Services.</li>
          <li>You should not rely on the Services as the sole basis for high-impact decisions affecting legal rights, finances, employment, health, safety, or access to essential services.</li>
          <li>Outputs may be similar or identical for different users, and we do not guarantee that Outputs are protectable by intellectual property laws.</li>
        </ul>
      </section>

      <section id="acceptable-use">
        <h2>6. Acceptable Use</h2>
        <p>You may not use the Services to:</p>
        <ul>
          <li>Violate any applicable law, regulation, contractual obligation, or third-party right.</li>
          <li>Submit, generate, or distribute unlawful, harmful, abusive, deceptive, infringing, or privacy-invasive content.</li>
          <li>Build or facilitate malware, phishing, credential theft, spam, harassment, surveillance, or unauthorized access.</li>
          <li>Attempt to reverse engineer, scrape, crawl, benchmark, overload, or bypass rate limits, security controls, access controls, or usage limits.</li>
          <li>Use the Services to make automated high-impact decisions without appropriate human review and legal compliance.</li>
          <li>Misrepresent AI-generated content as human-created where that would be deceptive or unlawful.</li>
          <li>Use the Services to develop competing models or services in a manner that violates these Terms or applicable law.</li>
          <li>Upload data you are not authorized to process or share.</li>
        </ul>
        <p>
          We may investigate suspected violations and may remove content, restrict features, suspend accounts, or terminate access.
        </p>
      </section>

      <section id="billing">
        <h2>7. Credits, Subscriptions, Billing, and Refunds</h2>
        <p>
          {productBrand.name} may offer free access, paid subscriptions, credit packs, usage-based billing, trials, or enterprise plans. Plan details, pricing, features, credits, limits, and renewal terms are shown at checkout, on our pricing page, or in an applicable order form.
        </p>
        <ul>
          <li><strong>Credits:</strong> Credits measure usage of agent work and other paid features. Credits may be granted through plans, promotions, or purchases. Credits have no cash value and are not transferable unless we say otherwise.</li>
          <li><strong>Subscriptions:</strong> Paid subscriptions may renew automatically unless canceled before the renewal date. You authorize us and our payment processors to charge applicable fees and taxes.</li>
          <li><strong>Payment processors:</strong> Payments are processed by third parties such as Stripe. Their terms and privacy policies apply to their processing.</li>
          <li><strong>Refunds:</strong> Unless required by law or stated in a separate refund policy, fees are non-refundable. We may deny refunds where we reasonably believe an account violated these Terms, abused the Services, or used credits after purchase.</li>
          <li><strong>Changes:</strong> We may change pricing, credits, features, or plans prospectively. If a change materially affects an active paid subscription, we will provide notice as required by law or by the checkout terms.</li>
        </ul>
      </section>

      <section id="third-party">
        <h2>8. Third-Party Services and Integrations</h2>
        <p>
          The Services may integrate with third-party tools such as Google Workspace, Gmail, Slack, Notion, Feishu/Lark, Stripe, authentication providers, AI model providers, hosting providers, search providers, analytics providers, and other services.
        </p>
        <p>
          Third-party services are governed by their own terms and privacy policies. We are not responsible for third-party services, data practices, failures, or content. You are responsible for ensuring that your use of integrations complies with applicable third-party terms and your own obligations.
        </p>
      </section>

      <section id="ip">
        <h2>9. {productBrand.name} IP and Feedback</h2>
        <p>
          {productBrand.name} and our licensors own the Services, including software, interfaces, designs, trademarks, logos, models, workflows, prompts, systems, documentation, and other technology, except for Your Content and Outputs as described above.
        </p>
        <p>
          You may provide feedback, ideas, or suggestions. We may use feedback without restriction or compensation to you.
        </p>
      </section>

      <section id="confidentiality">
        <h2>10. Confidentiality</h2>
        <p>
          If you receive non-public information about {productBrand.name}, including product plans, security details, pricing terms, benchmarks, or beta features, you must keep it confidential and use it only for the purpose for which it was disclosed.
        </p>
      </section>

      <section id="termination">
        <h2>11. Suspension and Termination</h2>
        <p>
          You may stop using the Services at any time. We may suspend or terminate your access if we believe you violated these Terms, create risk for {productBrand.name} or others, fail to pay fees, or if required by law.
        </p>
        <p>
          After termination, your right to use the Services ends. Sections that by their nature should survive termination will survive, including ownership, payment obligations, disclaimers, limitation of liability, indemnity, dispute provisions, and confidentiality.
        </p>
      </section>

      <section id="disclaimers">
        <h2>12. Disclaimers</h2>
        <p>
          To the fullest extent permitted by law, the Services and all Outputs are provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express, implied, statutory, or otherwise. We disclaim warranties of merchantability, fitness for a particular purpose, title, non-infringement, accuracy, availability, security, and uninterrupted operation.
        </p>
        <p>
          We do not warrant that the Services will be error-free, secure, available at all times, or that Outputs will be accurate, complete, unique, legally compliant, or suitable for your needs.
        </p>
      </section>

      <section id="liability">
        <h2>13. Limitation of Liability</h2>
        <p>
          Notwithstanding anything to the contrary and to the fullest extent permitted by law, under no circumstances shall either party, its affiliates, or any licensors or suppliers of {productBrand.name} be liable for:
        </p>
        <ol type="a">
          <li>Any consequential, indirect, special, incidental, or punitive damages;</li>
          <li>Any loss of profits, business, revenue, anticipated savings, or unnecessary expenses;</li>
          <li>Any loss, damage, or interruption of data, networks, information systems, reputation, or goodwill;</li>
          <li>The cost of procuring any substitute goods or services.</li>
        </ol>
        <p>
          To the fullest extent permitted by law, the aggregate liability of {productBrand.name} and its affiliates under or in connection with this agreement, the software, and the services shall not exceed the total amount you actually paid to {productBrand.name} under this agreement in the three (3) months preceding the event giving rise to the liability (if any).
        </p>
        <p>
          The above exclusions and limitations shall apply:
        </p>
        <ol type="a">
          <li>To the fullest extent permitted by applicable law;</li>
          <li>Even if a party has been advised of, or should have been aware of, the possibility of such losses, damages, or costs;</li>
          <li>Even if any remedy provided in this agreement fails of its essential purpose;</li>
          <li>Regardless of the theory or basis of liability, whether in contract, tort (including negligence or breach of statutory duty), misrepresentation, restitution, or otherwise.</li>
        </ol>
      </section>

      <section id="indemnity">
        <h2>14. Indemnification</h2>
        <p>
          To the fullest extent permitted by law, you will indemnify, defend, and hold harmless {productBrand.name} and our affiliates, officers, employees, agents, suppliers, and licensors from claims, liabilities, damages, losses, and expenses arising from or related to your use of the Services, Your Content, your violation of these Terms, or your violation of law or third-party rights.
        </p>
      </section>

      <section id="law">
        <h2>15. Governing Law and Disputes</h2>
        <p>
          These Terms are governed by the laws of Hong Kong, without regard to conflict-of-law rules. The parties will first attempt to resolve disputes informally by contacting each other.
        </p>
        <p>
          If you have any dispute, claim, or controversy arising out of or relating to these Terms or the Services, you agree to first attempt to resolve the dispute informally by contacting {productBrand.name} at <a href={`mailto:${productBrand.supportEmail}`}>{productBrand.supportEmail}</a>.
        </p>
      </section>

      <section id="changes">
        <h2>16. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. If we make material changes, we will update the &quot;Last updated&quot; date and may provide notice through the Services or by email. Unless we state otherwise, updated Terms become effective when posted. Your continued use of the Services after the effective date means you accept the updated Terms.
        </p>
      </section>

      <section id="misc">
        <h2>17. Miscellaneous</h2>
        <p>
          These Terms and the Privacy Policy are the entire agreement between you and {productBrand.name} regarding the Services unless a separate written agreement applies. If any provision is unenforceable, the remaining provisions remain in effect. Our failure to enforce a provision is not a waiver. You may not assign these Terms without our consent; we may assign them as part of a merger, acquisition, reorganization, or sale of assets.
        </p>
      </section>

      <section id="contact">
        <h2>18. Contact</h2>
        <p>
          If you have questions about these Terms, contact us at <a href={`mailto:${productBrand.supportEmail}`}>{productBrand.supportEmail}</a>.
        </p>
      </section>
    </LegalPage>
  );
}
