-- Persist daily briefings generated by the executive assistant.
CREATE TABLE "executive_briefings" (
    "id" TEXT NOT NULL,
    "dateKey" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "sections" JSONB NOT NULL,
    "sources" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "investorId" TEXT NOT NULL,

    CONSTRAINT "executive_briefings_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "executive_briefings_investorId_dateKey_key" ON "executive_briefings"("investorId", "dateKey");
CREATE INDEX "executive_briefings_investorId_updatedAt_idx" ON "executive_briefings"("investorId", "updatedAt");

ALTER TABLE "executive_briefings"
ADD CONSTRAINT "executive_briefings_investorId_fkey"
FOREIGN KEY ("investorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
